//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInfo
    {
        public int Id { get; set; }
        public int ManagerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SaleInfo { get; set; }
    
        public virtual Manager Managers { get; set; }
        public virtual SaleInfo SaleInfo1 { get; set; }
    }
}
