//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInfo
    {
        public int Id { get; set; }
        public int ManagerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SaleInfoId { get; set; }
    
        public virtual Managers Managers { get; set; }
        public virtual SaleInfo SaleInfo { get; set; }
    }
}
