//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInfo
    {
        public SaleInfo()
        {
            this.FileInfo = new HashSet<FileInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string СurrencyСode { get; set; }
    
        public virtual Client Clients { get; set; }
        public virtual ICollection<FileInfo> FileInfo { get; set; }
        public virtual Product Products { get; set; }
    }
}
