//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInfo
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public int FileInfoId { get; set; }
        public int Cost { get; set; }
        public string Currency { get; set; }
    
        public virtual Client Clients { get; set; }
        public virtual FileInfo FileInfo { get; set; }
        public virtual Product Products { get; set; }
    }
}
